I had error while executing test_target_builder.py: AttributeError: module 'numpy' has no attribute 'int'.
numpy.int was deprecated in NumPy 1.20 and was removed in NumPy 1.24.

Solution: replace np.int by np.int_